FROM gcc:8.2.0-centos7 as gccbuilder
FROM python:3.7-centos7

COPY --from=gccbuilder /usr/local/gcc-8.2.0 /usr/local/gcc-8.2.0

RUN yum install -y \
	    gmp-devel \
	    mpfr-devel \
	    libmpc-devel && \
	    pip install --upgrade pip --no-cache-dir && pip install paddlepaddle==2.2.0 -i https://mirror.baidu.com/pypi/simple \
	    --no-cache-dir
